### ISSUE TITLE
关于weights中的soap_60.pth文件

### ISSUE THREAD

**Issue by pibaopi** [skywoodsz/aubo_pick_up_with_6D#1]
哈喽老哥，可以把你的weights中的soap文件分享一下吗，最近在做dope的物体位姿检测，看到你这边成功了，也想复现一下，非常感谢！

**Comment by skywoodsz** [comment]
> 哈喽老哥，可以把你的weights中的soap文件分享一下吗，最近在做dope的物体位姿检测，看到你这边成功了，也想复现一下，非常感谢！

抱歉这个是自己训练的，没有办法分享，你可以用dope自己训练好的
